cout << endl << "- Nhap ho va ten: "; 
//    getenter;
    getline(cin, P.Name);
    //cin >> P.Name;
    cout << "- Nhap so dien thoai: ";
//    getenter;
    getline(cin, P.SDT);
    cout << "- Nhap ngay thang nam sinh (dd/mm/yyyy): ";
//    getenter;
    getline(cin, P.DateOfBirth);
    cout << "- Nhap so can cuoc cong dan: ";
//    getenter;
    getline(cin, P.CCCD);
    removeSpaces(P.CCCD);
    cout << "- Nhap dia chi (ex: 01 Le Duan, Hai Chau, Da Nang): ";
//    getenter;
    getline(cin, P.Address);
    cout << "- Nhap mau khau: ";
//   getenter;
    getline(cin, P.Password);